#!/usr/bin/env bash
# fix-oss-checksums.sh — fix "NotImplemented: Aws MultiChunkedEncoding STREAMING-UNSIGNED-PAYLOAD-TRAILER"
# (boto3 >= 1.36 default flexible checksums are not supported by Aliyun OSS).
# Deploys the fixed storage.py, rebuilds backend+worker, restarts nginx, then re-processes
# any media rows stuck in failed/processing so they reach 'ready'.
set -euo pipefail

cd /opt/wedding-app/backend/src/services
cp storage.py storage.py.bak 2>/dev/null || true
base64 -d > storage.py <<'B64_STORAGE'
IiIiT2JqZWN0LXN0b3JhZ2UgYWJzdHJhY3Rpb24gKEFEUi0wMDMpLg0KDQpUd28gaW50ZXJjaGFuZ2VhYmxlIGJhY2tlbmRzIGJlaGluZCBvbmUgaW50ZXJmYWNlOg0KLSBgUzNTdG9yYWdlYCAg4oCUIFMzLWNvbXBhdGlibGUgKE1pbklPIGluIGRldiwgQWxpQ2xvdWQgT1NTIGluIHByb2QpIHZpYSBib3RvMywgd2l0aA0KICBwcmVzaWduZWQtUFVUIGRpcmVjdCB1cGxvYWQuDQotIGBMb2NhbFN0b3JhZ2VgIOKAlCBmaWxlc3lzdGVtIGJhY2tlbmQgZm9yIGRldi90ZXN0IHdpdGggbm8gZXh0ZXJuYWwgaW5mcmEuIEl0cw0KICAicHJlc2lnbmVkIiBVUkwgcG9pbnRzIGF0IGEgbG9jYWwgZGV2IHVwbG9hZCBlbmRwb2ludCB0aGF0IHN0YW5kcyBpbiBmb3IgdGhlIGRpcmVjdA0KICBjbGllbnTihpJPU1MgUFVULg0KDQpgZ2V0X3N0b3JhZ2UoKWAgcGlja3MgdGhlIGJhY2tlbmQgZnJvbSBzZXR0aW5ncyBhbmQgaXMgY2FjaGVkIHBlciBwcm9jZXNzLg0KIiIiDQoNCmZyb20gZnVuY3Rvb2xzIGltcG9ydCBscnVfY2FjaGUNCmZyb20gcGF0aGxpYiBpbXBvcnQgUGF0aA0KZnJvbSB0eXBpbmcgaW1wb3J0IFByb3RvY29sDQoNCmZyb20gLi5jb25maWcgaW1wb3J0IGdldF9zZXR0aW5ncw0KDQoNCmNsYXNzIFN0b3JhZ2UoUHJvdG9jb2wpOg0KICAgIGRlZiBwcmVzaWduZWRfcHV0X3VybChzZWxmLCBrZXk6IHN0ciwgY29udGVudF90eXBlOiBzdHIpIC0+IHN0cjogLi4uDQogICAgIyBTaWduZWQgcmVhZCBVUkwgZm9yIHByaXZhdGUgYnVja2V0czsgTm9uZSB3aGVuIHRoZSBiYWNrZW5kIGNhbid0IHByZXNpZ24NCiAgICAjIChMb2NhbFN0b3JhZ2Ug4oCUIHRoZSBjYWxsZXIgdGhlbiBzZXJ2ZXMgdGhlIGJ5dGVzIGl0c2VsZikuDQogICAgZGVmIHByZXNpZ25lZF9nZXRfdXJsKHNlbGYsIGtleTogc3RyLCBleHBpcmVzOiBpbnQgPSAzNjAwKSAtPiBzdHIgfCBOb25lOiAuLi4NCiAgICBkZWYgcHV0KHNlbGYsIGtleTogc3RyLCBkYXRhOiBieXRlcykgLT4gTm9uZTogLi4uDQogICAgZGVmIGdldChzZWxmLCBrZXk6IHN0cikgLT4gYnl0ZXM6IC4uLg0KICAgIGRlZiBleGlzdHMoc2VsZiwga2V5OiBzdHIpIC0+IGJvb2w6IC4uLg0KICAgIGRlZiBkZWxldGUoc2VsZiwga2V5OiBzdHIpIC0+IE5vbmU6IC4uLg0KDQoNCmNsYXNzIExvY2FsU3RvcmFnZToNCiAgICAiIiJGaWxlc3lzdGVtLWJhY2tlZCBzdG9yYWdlIHJvb3RlZCBhdCBgYGJhc2VfZGlyYGAuIiIiDQoNCiAgICBkZWYgX19pbml0X18oc2VsZiwgYmFzZV9kaXI6IHN0cikgLT4gTm9uZToNCiAgICAgICAgc2VsZi5iYXNlID0gUGF0aChiYXNlX2RpcikNCiAgICAgICAgc2VsZi5iYXNlLm1rZGlyKHBhcmVudHM9VHJ1ZSwgZXhpc3Rfb2s9VHJ1ZSkNCg0KICAgIGRlZiBfcGF0aChzZWxmLCBrZXk6IHN0cikgLT4gUGF0aDoNCiAgICAgICAgcGF0aCA9IHNlbGYuYmFzZSAvIGtleQ0KICAgICAgICBwYXRoLnBhcmVudC5ta2RpcihwYXJlbnRzPVRydWUsIGV4aXN0X29rPVRydWUpDQogICAgICAgIHJldHVybiBwYXRoDQoNCiAgICBkZWYgcHJlc2lnbmVkX3B1dF91cmwoc2VsZiwga2V5OiBzdHIsIGNvbnRlbnRfdHlwZTogc3RyKSAtPiBzdHI6DQogICAgICAgICMgRGV2IHN0YW5kLWluIGZvciBhIHJlYWwgcHJlc2lnbmVkIE9TUyBVUkw7IHRoZSBjbGllbnQgUFVUcyBieXRlcyBoZXJlLg0KICAgICAgICByZXR1cm4gZiIvYXBpL3YxL21lZGlhL3VwbG9hZC9yYXc/a2V5PXtrZXl9Ig0KDQogICAgZGVmIHByZXNpZ25lZF9nZXRfdXJsKHNlbGYsIGtleTogc3RyLCBleHBpcmVzOiBpbnQgPSAzNjAwKSAtPiBzdHIgfCBOb25lOg0KICAgICAgICByZXR1cm4gTm9uZQ0KDQogICAgZGVmIHB1dChzZWxmLCBrZXk6IHN0ciwgZGF0YTogYnl0ZXMpIC0+IE5vbmU6DQogICAgICAgIHNlbGYuX3BhdGgoa2V5KS53cml0ZV9ieXRlcyhkYXRhKQ0KDQogICAgZGVmIGdldChzZWxmLCBrZXk6IHN0cikgLT4gYnl0ZXM6DQogICAgICAgIHJldHVybiBzZWxmLl9wYXRoKGtleSkucmVhZF9ieXRlcygpDQoNCiAgICBkZWYgZXhpc3RzKHNlbGYsIGtleTogc3RyKSAtPiBib29sOg0KICAgICAgICByZXR1cm4gKHNlbGYuYmFzZSAvIGtleSkuZXhpc3RzKCkNCg0KICAgIGRlZiBkZWxldGUoc2VsZiwga2V5OiBzdHIpIC0+IE5vbmU6DQogICAgICAgIChzZWxmLmJhc2UgLyBrZXkpLnVubGluayhtaXNzaW5nX29rPVRydWUpDQoNCg0KY2xhc3MgUzNTdG9yYWdlOg0KICAgICIiIlMzLWNvbXBhdGlibGUgYmFja2VuZCAoTWluSU8gLyBBbGlDbG91ZCBPU1MpLiIiIg0KDQogICAgZGVmIF9faW5pdF9fKA0KICAgICAgICBzZWxmLA0KICAgICAgICBlbmRwb2ludDogc3RyIHwgTm9uZSwNCiAgICAgICAgYWNjZXNzX2tleTogc3RyLA0KICAgICAgICBzZWNyZXRfa2V5OiBzdHIsDQogICAgICAgIGJ1Y2tldDogc3RyLA0KICAgICAgICByZWdpb246IHN0ciB8IE5vbmUgPSBOb25lLA0KICAgICkgLT4gTm9uZToNCiAgICAgICAgaW1wb3J0IGJvdG8zICAjIGltcG9ydGVkIGxhemlseSBzbyBsb2NhbC9kZXYgbmVlZHMgbm8gYm90bzMNCiAgICAgICAgZnJvbSBib3RvY29yZS5jb25maWcgaW1wb3J0IENvbmZpZw0KDQogICAgICAgIHNlbGYuYnVja2V0ID0gYnVja2V0DQogICAgICAgICMgQWxpQ2xvdWQgT1NTIHNpZ25zIHdpdGggU2lnVjQsIHdoaWNoIHJlcXVpcmVzIGEgcmVnaW9uIChlLmcuIGNuLWJlaWppbmcgZm9yDQogICAgICAgICMgb3NzLWNuLWJlaWppbmcpOyB3aXRob3V0IGl0IHByZXNpZ25pbmcgcmFpc2VzIE5vUmVnaW9uRXJyb3IuIE1pbklPIGFjY2VwdHMgYW55Lg0KICAgICAgICAjIE9TUyBhbHNvIHJlamVjdHMgcGF0aC1zdHlsZSBVUkxzIChTZWNvbmRMZXZlbERvbWFpbkZvcmJpZGRlbiksIHNvIHJlcXVlc3RzDQogICAgICAgICMgbXVzdCBhZGRyZXNzIHRoZSBidWNrZXQgYXMgYSB2aXJ0dWFsIGhvc3Q6IGJ1Y2tldC5vc3MtY24tYmVpamluZy5hbGl5dW5jcy5jb20uDQogICAgICAgICMgTWluSU8gKGRldikgaGFzIG5vIE1JTklPX0RPTUFJTiwgc28gaXQgbmVlZHMgcGF0aC1zdHlsZSDigJQgcGljayBwZXIgZW5kcG9pbnQuDQogICAgICAgIGlzX29zcyA9IGVuZHBvaW50IGlzIG5vdCBOb25lIGFuZCAiYWxpeXVuY3MuY29tIiBpbiBlbmRwb2ludA0KICAgICAgICBzZWxmLmNsaWVudCA9IGJvdG8zLmNsaWVudCgNCiAgICAgICAgICAgICJzMyIsDQogICAgICAgICAgICBlbmRwb2ludF91cmw9ZW5kcG9pbnQsDQogICAgICAgICAgICByZWdpb25fbmFtZT1yZWdpb24sDQogICAgICAgICAgICBhd3NfYWNjZXNzX2tleV9pZD1hY2Nlc3Nfa2V5LA0KICAgICAgICAgICAgYXdzX3NlY3JldF9hY2Nlc3Nfa2V5PXNlY3JldF9rZXksDQogICAgICAgICAgICBjb25maWc9Q29uZmlnKA0KICAgICAgICAgICAgICAgIHNpZ25hdHVyZV92ZXJzaW9uPSJzM3Y0IiwNCiAgICAgICAgICAgICAgICAjIGJvdG8zID49IDEuMzYgYWRkcyBmbGV4aWJsZSBjaGVja3N1bXMgdG8gc3RyZWFtaW5nIHVwbG9hZHMgYnkgZGVmYXVsdCwNCiAgICAgICAgICAgICAgICAjIGVuY29kaW5nIHRoZSBib2R5IGFzIFNUUkVBTUlORy1VTlNJR05FRC1QQVlMT0FELVRSQUlMRVIg4oCUIE9TUyByZWplY3RzDQogICAgICAgICAgICAgICAgIyB0aGF0IHdpdGggTm90SW1wbGVtZW50ZWQuICJ3aGVuX3JlcXVpcmVkIiByZXN0b3JlcyB0aGUgY2xhc3NpYw0KICAgICAgICAgICAgICAgICMgYmVoYXZpb3IgKGNoZWNrc3VtIG9ubHkgd2hlbiB0aGUgb3BlcmF0aW9uIGRlbWFuZHMgb25lKS4NCiAgICAgICAgICAgICAgICByZXF1ZXN0X2NoZWNrc3VtX2NhbGN1bGF0aW9uPSJ3aGVuX3JlcXVpcmVkIiwNCiAgICAgICAgICAgICAgICByZXNwb25zZV9jaGVja3N1bV92YWxpZGF0aW9uPSJ3aGVuX3JlcXVpcmVkIiwNCiAgICAgICAgICAgICAgICBzMz17ImFkZHJlc3Npbmdfc3R5bGUiOiAidmlydHVhbCIgaWYgaXNfb3NzIGVsc2UgInBhdGgifSwNCiAgICAgICAgICAgICksDQogICAgICAgICkNCg0KICAgIGRlZiBwcmVzaWduZWRfcHV0X3VybChzZWxmLCBrZXk6IHN0ciwgY29udGVudF90eXBlOiBzdHIpIC0+IHN0cjoNCiAgICAgICAgIyBDb250ZW50LVR5cGUgbXVzdCBiZSBwYXJ0IG9mIHRoZSBzaWduYXR1cmU6IHRoZSBjbGllbnQgUFVUcyB3aXRoIGl0LCBhbmQgT1NTDQogICAgICAgICMgKHVubGlrZSBNaW5JTykgcmVqZWN0cyB0aGUgcmVxdWVzdCB3aXRoIFNpZ25hdHVyZURvZXNOb3RNYXRjaCBvdGhlcndpc2UuDQogICAgICAgIHJldHVybiBzZWxmLmNsaWVudC5nZW5lcmF0ZV9wcmVzaWduZWRfdXJsKA0KICAgICAgICAgICAgInB1dF9vYmplY3QiLA0KICAgICAgICAgICAgUGFyYW1zPXsiQnVja2V0Ijogc2VsZi5idWNrZXQsICJLZXkiOiBrZXksICJDb250ZW50VHlwZSI6IGNvbnRlbnRfdHlwZX0sDQogICAgICAgICAgICBFeHBpcmVzSW49MzYwMCwNCiAgICAgICAgKQ0KDQogICAgZGVmIHByZXNpZ25lZF9nZXRfdXJsKHNlbGYsIGtleTogc3RyLCBleHBpcmVzOiBpbnQgPSAzNjAwKSAtPiBzdHIgfCBOb25lOg0KICAgICAgICAjIFNpZ25lZCBHRVQgZm9yIGEgcHJpdmF0ZSBidWNrZXQuIE9TUy9TMyBzZXJ2ZSBIVFRQIFJhbmdlIHJlcXVlc3RzIG5hdGl2ZWx5LA0KICAgICAgICAjIHdoaWNoIDx2aWRlbz4gc2Vla2luZyAoaU9TIFNhZmFyaSByZXF1aXJlcyAyMDYgcmVzcG9uc2VzKSBuZWVkcywgYW5kIHRoaXMNCiAgICAgICAgIyBrZWVwcyBsYXJnZSBtZWRpYSBieXRlcyBvdXQgb2YgdGhlIGJhY2tlbmQgcHJvY2VzcyBlbnRpcmVseS4NCiAgICAgICAgcmV0dXJuIHNlbGYuY2xpZW50LmdlbmVyYXRlX3ByZXNpZ25lZF91cmwoDQogICAgICAgICAgICAiZ2V0X29iamVjdCIsDQogICAgICAgICAgICBQYXJhbXM9ew0KICAgICAgICAgICAgICAgICJCdWNrZXQiOiBzZWxmLmJ1Y2tldCwNCiAgICAgICAgICAgICAgICAiS2V5Ijoga2V5LA0KICAgICAgICAgICAgICAgICMgQ29udGVudCBpcyBpbW11dGFibGUgKGtleXMgZW1iZWQgdGhlIGZpbGUgaGFzaCksIHNvIHRoZSBvYmplY3QgbWF5IGJlDQogICAgICAgICAgICAgICAgIyBjYWNoZWQgaGFyZCBldmVuIHRob3VnaCB0aGUgc2lnbmVkIFVSTCBpdHNlbGYgaXMgc2hvcnQtbGl2ZWQuDQogICAgICAgICAgICAgICAgIlJlc3BvbnNlQ2FjaGVDb250cm9sIjogInB1YmxpYywgbWF4LWFnZT0zMTUzNjAwMCwgaW1tdXRhYmxlIiwNCiAgICAgICAgICAgIH0sDQogICAgICAgICAgICBFeHBpcmVzSW49ZXhwaXJlcywNCiAgICAgICAgKQ0KDQogICAgZGVmIHB1dChzZWxmLCBrZXk6IHN0ciwgZGF0YTogYnl0ZXMpIC0+IE5vbmU6DQogICAgICAgIHNlbGYuY2xpZW50LnB1dF9vYmplY3QoQnVja2V0PXNlbGYuYnVja2V0LCBLZXk9a2V5LCBCb2R5PWRhdGEpDQoNCiAgICBkZWYgZ2V0KHNlbGYsIGtleTogc3RyKSAtPiBieXRlczoNCiAgICAgICAgcmV0dXJuIHNlbGYuY2xpZW50LmdldF9vYmplY3QoQnVja2V0PXNlbGYuYnVja2V0LCBLZXk9a2V5KVsiQm9keSJdLnJlYWQoKQ0KDQogICAgZGVmIGV4aXN0cyhzZWxmLCBrZXk6IHN0cikgLT4gYm9vbDoNCiAgICAgICAgZnJvbSBib3RvY29yZS5leGNlcHRpb25zIGltcG9ydCBDbGllbnRFcnJvcg0KDQogICAgICAgIHRyeToNCiAgICAgICAgICAgIHNlbGYuY2xpZW50LmhlYWRfb2JqZWN0KEJ1Y2tldD1zZWxmLmJ1Y2tldCwgS2V5PWtleSkNCiAgICAgICAgICAgIHJldHVybiBUcnVlDQogICAgICAgIGV4Y2VwdCBDbGllbnRFcnJvcjoNCiAgICAgICAgICAgIHJldHVybiBGYWxzZQ0KDQogICAgZGVmIGRlbGV0ZShzZWxmLCBrZXk6IHN0cikgLT4gTm9uZToNCiAgICAgICAgc2VsZi5jbGllbnQuZGVsZXRlX29iamVjdChCdWNrZXQ9c2VsZi5idWNrZXQsIEtleT1rZXkpDQoNCg0KQGxydV9jYWNoZQ0KZGVmIGdldF9zdG9yYWdlKCkgLT4gU3RvcmFnZToNCiAgICBzID0gZ2V0X3NldHRpbmdzKCkNCiAgICBpZiBzLnN0b3JhZ2VfYWNjZXNzX2tleSBhbmQgcy5zdG9yYWdlX3NlY3JldF9rZXk6DQogICAgICAgIHJldHVybiBTM1N0b3JhZ2UoDQogICAgICAgICAgICBzLnN0b3JhZ2VfZW5kcG9pbnQsDQogICAgICAgICAgICBzLnN0b3JhZ2VfYWNjZXNzX2tleSwNCiAgICAgICAgICAgIHMuc3RvcmFnZV9zZWNyZXRfa2V5LA0KICAgICAgICAgICAgcy5zdG9yYWdlX2J1Y2tldCwNCiAgICAgICAgICAgIHMuc3RvcmFnZV9yZWdpb24sDQogICAgICAgICkNCiAgICByZXR1cm4gTG9jYWxTdG9yYWdlKHMuc3RvcmFnZV9kaXIpDQo=
B64_STORAGE

echo "== Sanity check =="
grep -cF 'request_checksum_calculation="when_required"' storage.py

echo "== Rebuilding backend + worker (a few minutes) =="
cd /opt/wedding-app/infra
docker compose -f docker-compose.prod.yml build backend worker
docker compose -f docker-compose.prod.yml up -d backend worker
docker compose -f docker-compose.prod.yml restart nginx
sleep 15

echo "== Health =="
curl -sk https://localhost:8443/api/v1/health && echo

echo "== Re-processing failed/stuck media =="
docker compose -f docker-compose.prod.yml exec -T backend uv run python - <<'PYEOF'
import asyncio
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

from src.config import get_settings
from src.models.media import Media
from src.workers.media_processing import process_media


async def main() -> None:
    engine = create_async_engine(get_settings().database_url)
    async with AsyncSession(engine) as s:
        rows = (await s.execute(
            select(Media).where(Media.status.in_(["failed", "processing"]))
        )).scalars().all()
        if not rows:
            print("no failed/processing rows — nothing to repair")
            return
        for m in rows:
            m.status = "processing"  # let process_media accept it
            await process_media(s, m)
            await s.commit()
            await s.refresh(m)
            print(f"  id={m.id} ({m.filename}) -> {m.status}")


asyncio.run(main())
PYEOF

echo ""
echo "DONE. If every id above shows 'ready', uploads are fully fixed."
echo "Remaining manual step: add the OSS bucket CORS rule in the console (browser uploads need it)."