#!/usr/bin/env bash
# fix-media-object-route.sh — gallery images 404 because nginx sent /media-object/
# requests to the Next.js frontend instead of the backend (the spec mounts the route
# at app-root, not under /api/v1). Adds the proxy location; nginx.conf is volume-
# mounted so only a restart is needed — no image rebuild.
set -euo pipefail

cd /opt/wedding-app/infra/nginx
cp nginx.conf nginx.conf.bak 2>/dev/null || true
base64 -d > nginx.conf <<'B64_NGINX'
ZXZlbnRzIHt9DQoNCmh0dHAgew0KICAjIFdlYlNvY2tldCB1cGdyYWRlIHN1cHBvcnQNCiAgbWFwICRodHRwX3VwZ3JhZGUgJGNvbm5lY3Rpb25fdXBncmFkZSB7DQogICAgZGVmYXVsdCB1cGdyYWRlOw0KICAgICcnICAgICAgY2xvc2U7DQogIH0NCg0KICAjIFJhdGUgbGltaXRpbmcgKFQwODcpLiBUaGUgbG9naW4gcmF0ZSBtdXN0IHRvbGVyYXRlIGEgdmVudWUgZnVsbCBvZiBndWVzdHMgYmVoaW5kDQogICMgb25lIE5BVCBJUCDigJQgdGFyZ2V0ZWQgYnJ1dGUtZm9yY2UgcHJvdGVjdGlvbiBpcyB0aGUgYXBwLWxldmVsIGZhaWx1cmUgbG9ja291dCBpbg0KICAjIGJhY2tlbmQvc3JjL3NlcnZpY2VzL2xvZ2luX3Rocm90dGxlLnB5ICg0MjkgYWZ0ZXIgcmVwZWF0ZWQgd3JvbmcgcGFzc3dvcmRzKS4NCiAgbGltaXRfcmVxX3pvbmUgJGJpbmFyeV9yZW1vdGVfYWRkciB6b25lPWxvZ2luOjEwbSByYXRlPTEyMHIvbTsNCiAgbGltaXRfcmVxX3pvbmUgJGJpbmFyeV9yZW1vdGVfYWRkciB6b25lPWFwaToxMG0gcmF0ZT0zMHIvczsNCg0KICAjIFJlZGlyZWN0IEhUVFAg4oaSIEhUVFBTDQogIHNlcnZlciB7DQogICAgbGlzdGVuIDgwOw0KICAgIHNlcnZlcl9uYW1lIF87DQogICAgcmV0dXJuIDMwMSBodHRwczovLyRob3N0JHJlcXVlc3RfdXJpOw0KICB9DQoNCiAgc2VydmVyIHsNCiAgICBsaXN0ZW4gNDQzIHNzbDsNCiAgICBzZXJ2ZXJfbmFtZSBfOw0KDQogICAgc3NsX2NlcnRpZmljYXRlICAgICAvZXRjL25naW54L2NlcnRzL2Z1bGxjaGFpbi5wZW07DQogICAgc3NsX2NlcnRpZmljYXRlX2tleSAvZXRjL25naW54L2NlcnRzL3ByaXZrZXkucGVtOw0KDQogICAgY2xpZW50X21heF9ib2R5X3NpemUgNTUwbTsgICMgYWxsb3cgbGFyZ2UgdmlkZW8gdXBsb2FkcyAocHJveGllZCBwYXRocykNCg0KICAgICMgRlItMDM3OiBuZXZlciBpbmRleCB0aGlzIGV2ZW50LiBTZXQgYXQgdGhlIHNlcnZlciBsZXZlbCBzbyBpdCBhbHNvIGNvdmVycyBtZWRpYQ0KICAgICMgb2JqZWN0cyBhbmQgQVBJIHJlc3BvbnNlcywgd2hpY2ggY2Fycnkgbm8gSFRNTCA8bWV0YT4gdGFnIG9mIHRoZWlyIG93bi4NCiAgICBhZGRfaGVhZGVyIFgtUm9ib3RzLVRhZyAibm9pbmRleCwgbm9mb2xsb3csIG5vaW1hZ2VpbmRleCIgYWx3YXlzOw0KDQogICAgIyBMb2dpbiBpcyByYXRlLWxpbWl0ZWQgaGFyZGVzdCAoYnJ1dGUtZm9yY2UgcHJvdGVjdGlvbikuDQogICAgbG9jYXRpb24gPSAvYXBpL3YxL2F1dGgvbG9naW4gew0KICAgICAgbGltaXRfcmVxIHpvbmU9bG9naW4gYnVyc3Q9NjAgbm9kZWxheTsNCiAgICAgIHByb3h5X3Bhc3MgaHR0cDovL2JhY2tlbmQ6ODAwMDsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaG9zdDsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1SZWFsLUlQICRyZW1vdGVfYWRkcjsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtRm9yICRwcm94eV9hZGRfeF9mb3J3YXJkZWRfZm9yOw0KICAgICAgcHJveHlfc2V0X2hlYWRlciBYLUZvcndhcmRlZC1Qcm90byAkc2NoZW1lOw0KICAgIH0NCg0KICAgICMgQVBJDQogICAgbG9jYXRpb24gL2FwaS8gew0KICAgICAgbGltaXRfcmVxIHpvbmU9YXBpIGJ1cnN0PTYwIG5vZGVsYXk7DQogICAgICBwcm94eV9wYXNzIGh0dHA6Ly9iYWNrZW5kOjgwMDA7DQogICAgICBwcm94eV9zZXRfaGVhZGVyIEhvc3QgJGhvc3Q7DQogICAgICBwcm94eV9zZXRfaGVhZGVyIFgtUmVhbC1JUCAkcmVtb3RlX2FkZHI7DQogICAgICBwcm94eV9zZXRfaGVhZGVyIFgtRm9yd2FyZGVkLUZvciAkcHJveHlfYWRkX3hfZm9yd2FyZGVkX2ZvcjsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtUHJvdG8gJHNjaGVtZTsNCiAgICB9DQoNCiAgICAjIFdlYlNvY2tldC4gRG9uJ3QgbG9nIOKAlCB0aGUgYWNjZXNzIHRva2VuIHJpZGVzIGluIHRoZSBxdWVyeSBzdHJpbmcgYW5kIG11c3Qgbm90DQogICAgIyBsYW5kIGluIGFjY2VzcyBsb2dzIChUMDg3KS4NCiAgICBsb2NhdGlvbiAvd3Mgew0KICAgICAgYWNjZXNzX2xvZyBvZmY7DQogICAgICBwcm94eV9wYXNzIGh0dHA6Ly9iYWNrZW5kOjgwMDA7DQogICAgICBwcm94eV9odHRwX3ZlcnNpb24gMS4xOw0KICAgICAgcHJveHlfc2V0X2hlYWRlciBVcGdyYWRlICRodHRwX3VwZ3JhZGU7DQogICAgICBwcm94eV9zZXRfaGVhZGVyIENvbm5lY3Rpb24gJGNvbm5lY3Rpb25fdXBncmFkZTsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaG9zdDsNCiAgICB9DQoNCiAgICAjIE1lZGlhIG9iamVjdHM6IHNlcnZlZCBieSB0aGUgYmFja2VuZCBhdCBhcHAtcm9vdCAoTk9UIHVuZGVyIC9hcGkvdjEg4oCUIHRoZSBzcGVjDQogICAgIyBrZWVwcyB0aGUgcGF0aCBDRE4tc2hhcGVkLCBtYXRjaGluZyBORVhUX1BVQkxJQ19NRURJQV9CQVNFKS4gVGhlIGJhY2tlbmQgb25seQ0KICAgICMgYW5zd2VycyB3aXRoIGEgY2hlYXAgMzA3IHRvIGEgcHJlc2lnbmVkIE9TUyBVUkwgaW4gcHJvZCwgc28gbm8gcmF0ZSBsaW1pdCBoZXJlIOKAlA0KICAgICMgYSBnYWxsZXJ5IHBhZ2UgZWFzaWx5IGZhbnMgb3V0IGRvemVucyBvZiB0aHVtYm5haWwgcmVxdWVzdHMgZnJvbSBvbmUgY2xpZW50Lg0KICAgIGxvY2F0aW9uIC9tZWRpYS1vYmplY3QvIHsNCiAgICAgIHByb3h5X3Bhc3MgaHR0cDovL2JhY2tlbmQ6ODAwMDsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgSG9zdCAkaG9zdDsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1SZWFsLUlQICRyZW1vdGVfYWRkcjsNCiAgICAgIHByb3h5X3NldF9oZWFkZXIgWC1Gb3J3YXJkZWQtRm9yICRwcm94eV9hZGRfeF9mb3J3YXJkZWRfZm9yOw0KICAgICAgcHJveHlfc2V0X2hlYWRlciBYLUZvcndhcmRlZC1Qcm90byAkc2NoZW1lOw0KICAgIH0NCg0KICAgICMgRnJvbnRlbmQgKE5leHQuanMpDQogICAgbG9jYXRpb24gLyB7DQogICAgICBwcm94eV9wYXNzIGh0dHA6Ly9mcm9udGVuZDozMDAwOw0KICAgICAgcHJveHlfc2V0X2hlYWRlciBIb3N0ICRob3N0Ow0KICAgICAgcHJveHlfc2V0X2hlYWRlciBYLUZvcndhcmRlZC1Qcm90byAkc2NoZW1lOw0KICAgIH0NCiAgfQ0KfQ0K
B64_NGINX

echo "== Sanity check =="
grep -cF 'location /media-object/' nginx.conf

echo "== Validating config inside the nginx container =="
docker compose -f /opt/wedding-app/infra/docker-compose.prod.yml exec -T nginx nginx -t

echo "== Restarting nginx =="
cd /opt/wedding-app/infra
docker compose -f docker-compose.prod.yml restart nginx
sleep 5

echo "== Verify: media-object should now 307 to OSS =="
KEY=$(docker compose -f docker-compose.prod.yml exec -T backend uv run python - <<'PYEOF'
import asyncio
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine
from src.config import get_settings
from src.models.media import Media

async def m():
    engine = create_async_engine(get_settings().database_url)
    async with AsyncSession(engine) as s:
        r = (await s.execute(select(Media).where(Media.status == "ready").order_by(Media.id.desc()))).scalar_one()
        print(r.thumbnail_path)

asyncio.run(m())
PYEOF
)
echo "testing key: $KEY"
curl -sk -o /dev/null -w 'media-object status: %{http_code} (expect 307)\n' \
  "https://localhost:8443/media-object/$KEY"
curl -sk -L -o /dev/null -w 'full chain status: %{http_code} (expect 200)\n' \
  "https://localhost:8443/media-object/$KEY"

echo "DONE. Hard-refresh the gallery in your browser — images should now load."